const oopsContent = [
  "// Unit 1: Introduction to Classes in Java",
  "Object-oriented programming in Java revolves around the core concepts of encapsulation, inheritance, polymorphism, and data abstraction.",
  "The Java Virtual Machine interprets compiled bytecode, enabling the platform-independent nature of Java applications across different operating systems.",
  "Reflection in Java allows a program to inspect and modify its own structure and behavior at runtime, including accessing private fields and methods.",
  "The Java Development Kit provides the necessary tools, executables, and binaries to compile, debug, and run Java applications.",
  "Bytecode interpretation involves the JVM reading the intermediate class files and translating them into machine-specific instructions on the fly.",
  "Java data types are divided into primitive types, such as integers and booleans, and reference types, which point to objects in memory.",
  "Variables act as memory locations to store data, while operators and expressions manipulate these values to produce new results.",
  "Control structures like loops and conditional statements direct the flow of execution within a Java program based on logical evaluations.",
  "Arrays in Java are objects that store multiple variables of the same type in a contiguous block of memory with a fixed size.",
  "Searching algorithms like binary search and sorting algorithms like merge sort are fundamental operations applied to arrays and collections.",
  "Functions, known as methods in Java, encapsulate reusable blocks of code that perform specific tasks and optionally return a value.",
  "Abstract classes cannot be instantiated directly and often contain abstract methods that must be implemented by concrete subclasses.",
  "Static classes, methods, and variables belong to the class itself rather than to any specific instance, meaning they are shared among all objects.",
  "Inner classes are defined within the scope of another class and have access to the enclosing class's members, including private ones.",
  "Constructors are special methods invoked automatically when an object is created, used to initialize the state of the new instance.",
  "Function overloading allows multiple methods in the same class to share the same name provided their parameter lists are distinctly different.",
  "Method overriding occurs when a subclass provides a specific implementation for a method that is already defined in its parent class.",
  "Java supports single inheritance for classes using the extends keyword, but allows multiple inheritance of type through interface implementation.",
  "Interfaces define a contract of abstract methods that implementing classes must fulfill, promoting loose coupling and polymorphism.",
  "The this keyword refers to the current instance of the class, commonly used to resolve naming collisions between instance variables and parameters.",
  "The super keyword accesses members and constructors of the immediate parent class, allowing subclasses to invoke overridden functionality.",
  "Access control modifiers like public, private, protected, and default encapsulate data by restricting visibility to different parts of the program.",
  "Packages organize related classes and interfaces into namespaces, preventing naming conflicts and controlling access boundaries.",
  "Exception handling in Java uses try, catch, and finally blocks to gracefully manage runtime errors and maintain normal application flow.",
  "The exception hierarchy is rooted in the Throwable class, splitting into Error for severe system issues and Exception for recoverable conditions.",
  "The throw statement explicitly triggers an exception, while the throws clause in a method signature indicates that the caller must handle a checked exception.",
  "// Unit 2: IO Package and Multithreading",
  "The Java IO package provides a rich set of stream classes for reading from and writing to files, network sockets, and memory buffers.",
  "Input streams read data sequentially from a source, while output streams write data sequentially to a designated destination.",
  "Object serialization converts the state of a Java object into a byte stream, allowing it to be saved to a file or transmitted over a network.",
  "Deserialization is the reverse process, reconstructing the original object in memory from a previously serialized sequence of bytes.",
  "Filter streams wrap underlying base streams to provide additional functionality, such as buffering data to improve read and write performance.",
  "Pipe streams are used for inter-thread communication, allowing data written by one thread to be read directly by another thread without temporary files.",
  "The File class provides an abstract representation of file and directory pathnames, allowing programs to create, delete, and inspect files.",
  "A thread is a lightweight sub-process representing an independent path of execution within a broader Java application.",
  "The thread lifecycle consists of several states, including new, runnable, blocked, waiting, timed waiting, and terminated.",
  "Multithreading maximizes CPU utilization by allowing concurrent execution of multiple tasks, which is highly beneficial for interactive applications.",
  "While multithreading improves performance, it introduces complex issues such as race conditions, deadlocks, and thread starvation.",
  "Creating a thread in Java is accomplished either by extending the Thread class or by implementing the Runnable interface.",
  "Thread synchronization uses monitors and intrinsic locks to ensure that only one thread can access a critical section of code at a time.",
  "The synchronized keyword can be applied to methods or specific blocks of code to prevent concurrent modification of shared resources.",
  "// Unit 3: GUI and Database Connectivity",
  "Java Database Connectivity provides a standard API for connecting Java applications to various relational database management systems.",
  "The JDBC architecture relies on a driver manager that loads vendor-specific database drivers to translate Java calls into network protocols.",
  "Establishing a database connection requires a valid database URL, username, and password, returning a Connection object to manage the session.",
  "The Statement interface is used to execute static SQL queries and retrieve the results generated by the database.",
  "PreparedStatement pre-compiles SQL statements, improving execution speed for repeated queries and offering protection against SQL injection attacks.",
  "Common problems with raw JDBC include writing boilerplate code, managing resource closures manually, and dealing with complex checked exceptions.",
  "Spring Boot simplifies enterprise Java development by providing auto-configuration, embedded application servers, and opinionated default settings.",
  "Annotations in Spring Boot reduce boilerplate XML configuration by defining component behavior, routing, and dependencies directly in the source code.",
  "The difference between plain JDBC and Spring JDBC is that Spring eliminates boilerplate resource management and provides a more robust exception hierarchy.",
  "XML schemas and namespaces were traditionally used to configure Spring applications before annotation-based configuration became the standard.",
  "The Project Object Model file, or pom.xml, is central to Maven, managing project dependencies, plugins, and automated build configurations.",
  "The Spring JDBC Template streamlines database interactions by automatically handling connection acquisition, statement execution, and result set iteration.",
  "The Spring DriverManagerDataSource is a simple implementation of the standard DataSource interface used to configure database connection properties.",
  "A Plain Old Java Object is a simple, standard object not bound by framework-specific restrictions or interfaces.",
  "A Spring Bean is an object that is instantiated, assembled, and managed by the Spring IoC container throughout its lifecycle.",
  "Dependency injection in Spring automatically wires Beans together, promoting loose coupling and making applications significantly easier to test."
];
