const coaContent = [
  "// Unit I: Fundamentals of Computer Systems",
  "// Chapter 1.1: Basic Functional Units",
  "The basic functional units of a digital computer include the arithmetic logic unit, control unit, memory unit, and input-output unit that work together to execute instructions.",
  "The arithmetic logic unit performs all mathematical and logical operations required by the instruction set.",
  "The control unit generates timing and control signals that coordinate data movement between registers, memory, and the ALU.",
  "The memory unit stores both instructions and data, providing the processor with the information it needs during execution.",
  "The input-output unit manages communication between the computer and external devices such as keyboards, displays, and storage drives.",
  "Computer registers are high-speed storage locations within the CPU used to hold data, addresses, and intermediate results during instruction execution.",
  "Registers are built from flip-flops and are much faster than main memory, which is why they are used for critical temporary storage.",
  "Common registers include the accumulator, program counter, instruction register, memory address register, and general-purpose registers.",
  "The program counter holds the address of the next instruction to be fetched from memory, ensuring sequential execution unless a branch occurs.",
  "The instruction register holds the current instruction while it is being decoded and executed by the control unit.",
  "The system bus structure consists of the data bus for transferring data, the address bus for specifying memory locations, and the control bus for coordinating operations.",
  "The width of the data bus determines how many bits can be transferred in parallel during each bus cycle.",
  "The address bus width determines the maximum size of addressable memory, since n address lines can address 2^n locations.",
  "Control bus lines carry signals such as read, write, interrupt request, and clock that synchronize operations across the system.",
  "A bus cycle is the sequence of steps required to complete a single data transfer over the system bus.",
  "Overview of memory and I/O addressing includes memory-mapped I/O and isolated I/O schemes for accessing peripheral devices.",
  "In memory-mapped I/O, I/O devices share the same address space as main memory, so normal load and store instructions can access them.",
  "In isolated I/O, special IN and OUT instructions are used to access separate I/O address spaces, keeping memory and I/O addresses distinct.",
  
  "// Chapter 1.2: Data Representation and Arithmetic",
  "Fixed-point representation stores numbers with a fixed number of digits after the radix point while floating-point representation uses a significand and exponent for a wider range.",
  "Fixed-point numbers are simpler to implement in hardware and are often used in embedded systems where speed and predictability are critical.",
  "Floating-point numbers follow standards like IEEE 754, which defines formats for single precision (32-bit) and double precision (64-bit) values.",
  "In IEEE 754, a floating-point number is represented by a sign bit, an exponent field, and a fraction or mantissa field.",
  "In IEEE 754 single precision, 1 bit is used for sign, 8 bits for exponent, and 23 bits for the fraction.",
  "In IEEE 754 double precision, 1 bit is used for sign, 11 bits for exponent, and 52 bits for the fraction.",
  "Special IEEE 754 patterns represent infinities, NaNs, and denormalized numbers to handle exceptional cases gracefully.",
  "Addition and subtraction in fixed-point arithmetic follow binary rules with careful handling of overflow and the sign bit using two's complement.",
  "Two's complement representation allows subtraction to be performed as addition of a negated operand, simplifying hardware design.",
  "Overflow in fixed-point addition occurs when the result exceeds the range that can be represented with the given number of bits.",
  "A ripple-carry adder is simple but slow because the carry bit must propagate sequentially through every full adder stage.",
  "A carry-lookahead adder reduces computation time by calculating carry signals in advance based on generate and propagate logic.",
  "Multiplication algorithms such as Booth's algorithm reduce the number of partial products by examining consecutive bits of the multiplier.",
  "Booth's algorithm is particularly efficient when the multiplier has long runs of 0s or 1s, reducing the number of required addition operations.",
  "A Wallace tree multiplier uses a tree of half and full adders to compress partial products in parallel, significantly speeding up multiplication.",
  "Division algorithms like restoring and non-restoring division iteratively approximate the quotient by shifting and subtracting the divisor.",
  "BCD representation encodes each decimal digit in four bits while ASCII provides a standard seven-bit or eight-bit encoding for characters.",
  "Little-endian systems store the least significant byte of a multi-byte value at the lowest memory address whereas big-endian stores the most significant byte first.",
  
  "// Chapter 1.3: Instruction Set Architectures (ISA)",
  "Levels of programming languages range from high-level languages through assembly language down to machine instructions that the processor directly executes.",
  "Assembly language provides a symbolic representation of machine instructions, making low-level programming more readable while still closely tied to hardware.",
  "Machine instructions are binary-encoded commands that specify operations, operands, and addressing modes understood directly by the CPU.",
  "The machine cycle consists of the fetch cycle, decode cycle, and execute cycle while the bus cycle handles data transfers over the system bus.",
  "During the fetch phase, the instruction at the address in the program counter is read from memory into the instruction register.",
  "During decode, the control unit interprets the opcode and determines which operands and functional units are needed.",
  "During execute, the specified operation is performed, which may involve arithmetic, logic, memory access, or control flow changes.",
  "Addressing modes specify how the operand of an instruction is located and include immediate, direct, indirect, register, and relative addressing.",
  "Immediate addressing embeds the operand value directly within the instruction, avoiding an extra memory reference.",
  "Direct addressing specifies the memory address of the operand explicitly in the instruction.",
  "Indirect addressing uses a memory location that contains the actual address of the operand, allowing for pointers and dynamic data structures.",
  "Register addressing uses a register as the source or destination of the operand, which is faster than accessing main memory.",
  "Relative addressing adds a displacement to the program counter to compute the effective address, useful for branches and position-independent code.",
  "Indexed addressing uses an index register added to a base address, which is highly efficient for iterating through arrays.",
  "Instruction formats define the layout of opcode and operand fields within a machine instruction and vary between RISC and CISC designs.",
  "The zero-address instruction format relies exclusively on an implicit stack to source operands and store results.",
  
  "// Unit II: Processor Design",
  "// Chapter 2.1: CPU Organization and Datapath",
  "Accumulator-based CPU organization uses a single special register as the primary source and destination for most arithmetic operations.",
  "General register organization provides a set of general-purpose registers that can serve as source or destination for instructions.",
  "Stack organization uses a last-in first-out structure with push and pop operations often implemented with a stack pointer register.",
  "RISC architectures emphasize a small set of simple instructions that execute in a single cycle, relying heavily on compilers for optimization.",
  "CISC architectures aim to reduce the number of instructions per program by providing powerful, complex instructions directly in hardware.",
  "Modern processors often blend RISC and CISC ideas, using simple internal micro-operations to implement complex external instructions.",
  "A single-cycle datapath executes every instruction in one long clock cycle, meaning the clock period must be as long as the slowest instruction.",
  "A multi-cycle datapath breaks instructions into steps, taking multiple shorter clock cycles to complete, allowing components to be reused within the same instruction.",
  
  "// Chapter 2.2: Design of Control Unit",
  "A hardwired control unit uses combinational logic circuits to generate control signals based on the current instruction and state.",
  "Hardwired control is fast because control signals are produced directly by logic gates, but it is difficult to modify or extend.",
  "A micro-programmed control unit stores control signals as microinstructions in a control memory that is sequenced during instruction execution.",
  "Microprogramming makes it easier to implement complex instructions and to update the control logic without redesigning the hardware.",
  "In micro-programmed control, each machine instruction is executed as a sequence of micro-operations defined by microinstructions.",
  "A micro-instruction typically contains control fields that directly dictate the state of datapath control lines.",
  "Control memory can be implemented using ROM for fixed microprograms or writable memory for dynamically changeable control sequences.",
  
  "// Chapter 2.3: Pipelining and Hazards",
  "Instruction pipelining overlaps the fetch, decode, and execute stages of successive instructions to improve instruction throughput.",
  "Pipelining increases performance by keeping multiple instructions in different stages of execution simultaneously, similar to an assembly line.",
  "The ideal speedup of a pipeline is equal to the number of pipeline stages, assuming perfectly balanced stages and no hazards.",
  "Pipeline hazards include structural hazards from resource conflicts, data hazards from dependencies, and control hazards from branches.",
  "Structural hazards happen when two instructions in the pipeline simultaneously require the same hardware resource.",
  "Data hazards occur in pipelines when the execution of one instruction depends on the unavailable result of a prior instruction.",
  "Read-After-Write (RAW) is a true data dependency where an instruction needs a value produced by a preceding instruction.",
  "Write-After-Write (WAW) and Write-After-Read (WAR) are name dependencies that can be resolved by register renaming.",
  "Forwarding or bypassing resolves data hazards by directly passing results from the execution unit back to the input of the ALU.",
  "A hardware interlock stalls the pipeline when a hazard is detected, preventing incorrect results at the cost of reduced throughput.",
  "Control hazards arise when the pipeline makes the wrong decision on a branch prediction, necessitating a pipeline flush.",
  "Branch prediction attempts to guess the outcome of a conditional branch before it is executed to prevent pipeline stalls.",
  "A Branch Target Buffer (BTB) caches the destination addresses of recent branches to expedite instruction fetching.",
  "A 1-bit predictor remembers the last outcome of a branch, but suffers two mispredictions in a loop (entry and exit).",
  "A 2-bit saturating counter branch predictor requires a branch to deviate twice before changing its long-term prediction state.",
  "Delayed branching prevents pipeline stalls by executing the instruction immediately following a branch regardless of the branch outcome.",
  
  "// Unit III: Advanced Execution and ILP",
  "// Chapter 3.1: Superscalar and Out-of-Order Execution",
  "Instruction-Level Parallelism (ILP) refers to the potential for overlapping the execution of independent instructions in a program.",
  "Superscalar processors issue multiple independent instructions per cycle by utilizing multiple execution units concurrently.",
  "VLIW (Very Long Instruction Word) architectures rely on the compiler to pack independent operations into a single long instruction.",
  "Out-of-order execution allows a processor to execute instructions as soon as their operands are available rather than strictly following the program order.",
  "Tomasulo's algorithm enables dynamic scheduling and out-of-order execution by using reservation stations to track operands.",
  "Reservation stations hold instructions waiting for their operands to be computed, buffering them until the functional unit is free.",
  "Register renaming eliminates false data dependencies by mapping a small set of architectural registers to a larger set of physical registers.",
  "The Common Data Bus (CDB) broadcasts computed results to all reservation stations waiting for that specific data.",
  "A Reorder Buffer (ROB) tracks instructions in issue order and allows them to commit their results in program order, ensuring precise exceptions.",
  
  "// Unit IV: Memory Hierarchy",
  "// Chapter 4.1: Cache Design",
  "The memory hierarchy arranges storage devices from fast, expensive registers and cache through main memory down to slower, cheaper secondary storage.",
  "The principle of locality of reference states that programs tend to reuse data and instructions that were used recently or are near recently used ones.",
  "Temporal locality means recently accessed items are highly likely to be accessed again in the near future.",
  "Spatial locality means items stored in addresses near a recently accessed address are likely to be accessed soon.",
  "Cache memory reduces average memory access time by storing recently used blocks of main memory closer to the processor.",
  "Mapping functions determine where a main-memory block is placed in cache and include direct mapping, fully associative, and set-associative mapping.",
  "Direct mapped caches assign each memory block to exactly one cache line, simplifying hardware but increasing collision misses.",
  "In a fully associative cache, a memory block can be placed in any cache line, requiring parallel tag comparisons across the entire cache.",
  "Set-associative caching provides a middle ground, dividing the cache into sets where blocks can reside anywhere within a specific set.",
  "A cache address is divided into three fields: the tag for identification, the index for selecting the set, and the offset for selecting the byte within the block.",
  "Cache misses are categorized as Compulsory (cold start), Capacity (cache too small), or Conflict (collision in specific sets).",
  "Replacement algorithms such as Least Recently Used (LRU) and First-In First-Out (FIFO) decide which cache block to evict when a new block must be loaded.",
  "Write policies decide when modified data is written back to main memory and include write-through and write-back approaches.",
  "A write-through cache immediately writes modified data to both the cache and the backing main memory, ensuring consistency.",
  "A write-back cache defers writing modifications to main memory until the modified cache block is evicted, saving bus bandwidth.",
  "A dirty bit in a cache memory system indicates whether a block has been modified and needs to be written back to main memory.",
  "The valid bit in a cache tag directory specifies whether the corresponding cache line contains meaningful data.",
  
  "// Chapter 4.2: Virtual Memory",
  "Virtual memory gives each process the illusion of a large, contiguous private address space by translating virtual addresses to physical addresses.",
  "Address translation isolates processes from each other and prevents them from corrupting the memory of other applications or the operating system.",
  "The Memory Management Unit (MMU) performs address translation in hardware and enforces protection by checking access rights.",
  "Paging divides the address space into fixed-size pages and maps them to physical memory frames using a page table.",
  "A page fault occurs when a program attempts to access a page that is mapped in the virtual address space but is not currently loaded in physical memory.",
  "The Translation Lookaside Buffer (TLB) is a highly associative hardware cache within the MMU that stores recent virtual-to-physical address translations.",
  "A TLB miss requires the hardware or operating system to walk the page table in main memory to find the correct translation.",
  "Segmentation divides the address space into variable-sized logical segments, such as code, data, and stack, which reflects the program's logical structure.",
  "Thrashing occurs when the working set of a process cannot fit in available frames, causing excessive page faults and dropping CPU utilization to near zero.",
  
  "// Unit V: Interconnects and Multiprocessors",
  "// Chapter 5.1: Buses and I/O",
  "Peripheral devices communicate with the CPU through I/O interfaces that handle data formatting, buffering, and control signaling.",
  "Asynchronous data transfer uses handshaking signals, such as STROBE and ACKNOWLEDGE, so that devices with different speeds can exchange data reliably.",
  "Interrupt-driven I/O allows a device to signal the CPU that it needs attention, freeing the processor to do other work instead of continuously polling.",
  "An interrupt vector is a memory address provided by the interrupting device that points to the specific interrupt service routine.",
  "Direct Memory Access (DMA) allows a device to transfer blocks of data directly to or from memory without continuous CPU intervention.",
  "In cycle-stealing DMA, the DMA controller transfers one word at a time, briefly taking control of the bus from the CPU.",
  "In burst-mode DMA, the controller seizes the bus and transfers a large block of data consecutively before relinquishing control.",
  "USB and PCI Express (PCIe) are modern high-speed serial interfaces that have largely replaced older parallel buses due to better signal integrity.",
  "PCIe uses point-to-point serial links called lanes, which can be grouped together to multiply the available bandwidth.",
  "Daisy chaining connects devices in series so that an interrupt acknowledge signal is passed sequentially, granting priority to the first device in the chain.",
  
  "// Chapter 5.2: Parallel Processing and Multicore",
  "Flynn's taxonomy categorizes parallel architectures as SISD, SIMD, MISD, and MIMD based on the number of instruction and data streams.",
  "SIMD (Single Instruction, Multiple Data) architectures, like GPUs and vector processors, apply the same operation to an array of data simultaneously.",
  "MIMD (Multiple Instruction, Multiple Data) systems include multi-core CPUs where each core executes its own code on its own data.",
  "Hardware multithreading improves processor utilization by maintaining the state of multiple threads and switching between them quickly to hide stalls.",
  "Simultaneous Multithreading (SMT), known commercially as Hyper-Threading, allows instructions from multiple threads to be issued in the same clock cycle.",
  "Symmetric Multiprocessing (SMP) involves two or more identical processors connected to a single, shared main memory space.",
  "Non-Uniform Memory Access (NUMA) architectures assign local memory to individual processors, making local memory access much faster than remote memory access.",
  "Cache coherence protocols ensure that multiple processors with their own private caches maintain a consistent view of shared memory.",
  "Snooping protocols rely on all caches monitoring a shared bus to track memory transactions and invalidate or update shared blocks.",
  "Directory-based coherence protocols track which caches hold copies of a block using a centralized or distributed directory, scaling better than snooping.",
  "The MESI protocol maintains coherence using four states: Modified (dirty), Exclusive (clean, only copy), Shared (clean, multiple copies), and Invalid.",
  "False sharing occurs when two independent variables reside in the same cache block, causing unnecessary cache invalidations when different processors modify them.",
  
  "// Unit VI: Performance and Metrics",
  "// Chapter 6.1: Measuring Performance",
  "The CPU execution time of a program is determined by the number of instructions, the cycles per instruction (CPI), and the clock cycle time.",
  "Clock rate determines how many cycles a processor executes per second, but a higher clock rate does not guarantee better performance if the CPI is high.",
  "MIPS (Millions of Instructions Per Second) is an unreliable metric for comparing different ISAs because the amount of work per instruction varies.",
  "FLOPS (Floating-Point Operations Per Second) is heavily used to measure the performance of supercomputers and GPUs on scientific workloads.",
  "Amdahl's Law states that the overall performance improvement gained by optimizing a single part of a system is limited by the fraction of time that part is actually used.",
  "According to Amdahl's Law, if an enhancement speeds up 50% of a program by a factor of 10, the maximum theoretical total speedup is still less than 2x.",
  "Gustafson's Law provides an alternative view to Amdahl's Law, stating that as parallel computing power increases, the problem size also scales, making parallelization more beneficial.",
  "SPEC (Standard Performance Evaluation Corporation) provides standardized benchmark suites to evaluate and compare the integer and floating-point performance of processors.",
  "Dynamic Voltage and Frequency Scaling (DVFS) reduces power consumption by dynamically lowering the operating frequency and voltage when the CPU is under light load.",
  "Static power arises from leakage currents even when transistors are not switching, while dynamic power depends on the switching activity and capacitance.",
  "Clock gating reduces dynamic power consumption by disabling the clock signal to idle circuit blocks that are not currently needed.",
  "Power gating shuts off the supply voltage to unused blocks, reducing static leakage power at the cost of a longer wake-up time.",
  "The CPU-memory performance gap refers to the historical trend where processor execution speeds have increased at a much faster rate than DRAM latency improvements."
];